version: '3.3'

services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=bryan
      - POSTGRES_PASSWORD=Abc1234
    ports:
      - '5431:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql
